[package]
description = "Read GTFS (public transit timetables) files"
name = "gtfs-structures"
version = "0.20.0"
authors = ["Tristram Gräbener <tristramg@gmail.com>"]
repository = "https://github.com/rust-transit/gtfs-structure"
license = "MIT"
edition = "2018"

[features]
default = ["read-url"]
read-url = ["reqwest", "futures"]

[dependencies]
bytes = "0.4"
csv = "1.1"
derivative = "1.0"
serde = "1.0"
serde_derive = "1.0"
chrono = "0.4"
itertools = "0.8"
sha2 = "0.8"
zip = "0.5"
thiserror = "1"
rgb = "0.8"

futures = { version = "0.3", optional = true }
reqwest = { version = "0.10", optional = true, features = ["blocking", "rustls-tls"], default-features = false }
